baseurl = "/"
author = "BSidesROC"
builddrafts = false
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
pluralizelisttitles = false
publishdir = "public"
relativeURLs = false
theme = "cocoa-eh"
title = "BSidesROC"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "January 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Rochester's Hacker Conference"
logofile = "img/logo.png"
highlightjs = true
lang = "en"
sponsorLevels = ["Gold", "Silver", "Bronze", "In-Kind"]
sponsorYears = [2018, 2017, 2016, 2015]
thisYear = [2018]
