baseurl = "/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = false
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "BSidesROC"
title = "BSidesROC"
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "January 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Rochester's Hacker Conference"
logofile = "img/logo.png"
faviconfile = "img/favicon.ico"
highlightjs = true
lang = "en"
